apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: emmanuelz/udagram-frontend
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # resources:
        #  requests:
        #    cpu: 100m
        #    memory: "256Mi"
        #  limits:
        #    cpu: 1000m
        #    memory: "1Gi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer
