apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - image: emmanuelz/reverseproxy
        name: proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
         requests:
           cpu: 100m
           memory: "256Mi"
         limits:
           cpu: 1000m
           memory: "1Gi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: proxy
  type: LoadBalancer