language: node_js
node_js:
- 14

services:
- docker

script:
- docker-compose -f docker-compose-build.yaml build

# after build:
# - echo "$DOCKER_PASSWORD" | docker login -u emmanuelz --password-stdin
# # - docker push emmanuelz/reverseproxy
# # - docker push emmanuelz/udagram-api-user
# # - docker push emmanuelz/udagram-api-feed
# - docker push emmanuelz/udagram-frontend